name = "ThermiaAPI"
uuid = "6a9dcc7b-3034-4be4-928d-8fe7b0a7c174"
authors = ["Fredrik Bagge Carlson"]
version = "1.0.0-DEV"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
